@startuml

struct Msg_Header
{
    uint8_t addresses : sender_address + receiver_address
    uint16_t packerCounter
}
struct Payload
{
    uint16_t temperature
    uint16_t flameValue
    uint8_t  states
    uint16_t gasValue
    uint8_t batteryValue

}
struct LoRaMessage
{
    uint8_t msg_type
    Msg_Header header
    Payload payload
    uint8_t checksum
}
@enduml